### ISSUE TITLE
Dokumentation

### ISSUE THREAD

**Issue by TobbeWendt** [mickecamino/RT-datorn#1]
Jag har ett häfte/bok/specialtryck med alla RT-artiklar från Radio & Television, ska försöka ta mig tid att skanna in det så småningom.

**Comment by mickecamino** [comment]
Är det boken Bygg Själv utgiven av Radio & Television? 
Alla Radio & Television finns skannade här: [https://www.aef.se/Amatortidningar/Radio_och_Television/Radio_Television_oversikt.htm](url)
Det jag letar efter för dokumentation är byggbeskrivningar på de kort som inte fanns i tidningen. Och monitorlistningen.

**Comment by TobbeWendt** [comment]
Det är "Bygg själv nr 6, Datorer" som jag har + en massa kopior av artiklar i R&T.

**Comment by mickecamino** [comment]
Stänger denna så länge, jag har fått tag på boken och där fanns CÅ-8008-kortet som inte finns i RT-tidningarna

**Comment by mickecamino** [comment]
Stängd
